env:
  browser: true
  es6: true
  node: true
  jest/globals: true

extends:
  - 'indico'
  - 'indico/babel'
  - 'indico/react'
  - 'indico/prettier'
  - 'prettier/babel'
  - 'prettier/react'
  - 'plugin:jest/recommended'

settings:
  react:
    version: detect

plugins:
  - jest
